apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: myapp
  name: hello-app-deployment
  labels:
    app: hello-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
        - name: hello-app
          image: robert260398.azurecr.io/hello:latest
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: hello-service
  namespace: myapp
spec:
  selector:
    app: hello-app
  ports:
  - name: myapp
    protocol: TCP
    port: 8080
    targetPort: 8080

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  namespace: myapp

spec:
  ingressClassName: nginx
  defaultBackend:
    service: 
      name: hello-service
      port: 
        number: 8080